include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    flutter_style_todos: false
    sort_pub_dependencies: false
    file_names: false
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    always_put_required_named_parameters_first: false
