name: dart_lens
description: An intuitive and powerful tool for exploring and managing Dart and Flutter projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1

  # state management
  provider: ^6.0.5
  flutter_hooks: ^0.18.6
  json_annotation: ^4.8.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

  path: ^1.8.2
  file_picker: ^5.3.2

  # UI
  google_fonts: ^4.0.4
  flex_color_scheme: ^7.1.2
  flex_seed_scheme: ^1.3.0
  flextras: ^1.0.0
  lucide_icons: ^0.257.0

  analyzer: ^5.13.0

  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  pub_api_client: # ^2.4.0
    git:
      url: https://github.com/fluttertools/pub_api_client.git
      ref: 10e90ad7436843a1cb224a477e22fda35be5cd77

  clipboard: ^0.1.3
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  send_support_email:
    git:
      url: https://github.com/albemala/send_support_email.git
      ref: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  json_serializable: ^6.7.0

  very_good_analysis: ^5.0.0+1

  flutter_gen_runner: ^5.3.1
  icons_launcher: ^2.1.2
  package_rename: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

# bash scripts/generate-assets.bash
flutter_gen:
  output: lib/defines/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: false

# bash scripts/generate-app-icons.bash
icons_launcher:
  image_path: "assets/app-icon.png"
  platforms:
    macos:
      enable: true
      # image_path: "assets/app-icon-macos.png"
    windows:
      enable: true
      # image_path: 'assets/ic_logo_border.png'
    linux:
      enable: true
      # image_path: 'assets/ic_logo_border.png'
    web:
      enable: false
      # image_path: 'assets/ic_logo_border.png'
      # favicon_path: 'assets/ic_logo_round.png'
    android:
      enable: false
      # image_path: 'assets/ic_logo_border.png'
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: 'assets/ic_background.png'
      # adaptive_foreground_image: 'assets/ic_foreground.png'
      # adaptive_round_image: 'assets/ic_logo_round.png'
    ios:
      enable: false
      # image_path: 'assets/ic_logo_rectangle.png'

# dart run package_rename
package_rename_config:
  macos:
    app_name: DartLens
    package_name: app.dartlens
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.

  windows:
    app_name: DartLens
    organization: dartlens.app
    copyright_notice: Copyright © 2023 dartlens.app. All rights reserved.
    exe_name: DartLens

  linux:
    app_name: DartLens
    package_name: app.dartlens
    exe_name: DartLens
