platform :mac do

  lane :generate_certificates_profiles do |options|
    match(
      type: "development",
#       force_for_new_devices: true,
    )
    match(
      type: "appstore",
    )
    match(
      type: "developer_id",
      additional_cert_types: [
        "mac_installer_distribution",
        "developer_id_installer",
      ],
    )
  end

  lane :get_certificates_profiles do |options|
    match(
      type: "development",
      readonly: true,
    )
    match(
      type: "appstore",
      readonly: true,
    )
    match(
      type: "developer_id",
      additional_cert_types: [
        "mac_installer_distribution",
        "developer_id_installer",
      ],
      readonly: true,
    )
  end

  lane :build_standalone do |options|
    build_mac_app(
      scheme: "Runner",
      export_method: "developer-id",
      export_team_id: ENV["TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "app.dartlens" => "match Direct app.dartlens macos",
        },
      },
      output_directory: "build",
    )
  end

  lane :publish_standalone do |options|
    notarize(
      asc_provider: ENV["TEAM_ID"],
      package: "build/DartLens.app",
      print_log: true,
      verbose: true,
    )
  end

end
